EstadodeCuenta/EstadodeCuenta.WebAdmin/Controllers/DetallesController.cs
using EstadodeCuenta.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstadodeCuenta.WebAdmin.Controllers
{
    public class DetallesController : Controller
    {
        DetallesBL _DetallesBL;

        public DetallesController()
        {
            _DetallesBL = new DetallesBL();
        }

        // GET: Detalles
        public ActionResult Index()
        {
            var listadeDetalles = _DetallesBL.ObtenerDetalles();

            return View(listadeDetalles);
        }

        public ActionResult Crear()
        {
            var nuevadetalle = new detalle();

            return View(nuevadetalle);
        }

        [HttpPost]
        public ActionResult Crear(detalle detalle)
        {
            if (ModelState.IsValid)
            {
                if (detalle.Descripcion != detalle.Descripcion.Trim())
                {
                    ModelState.AddModelError("Descripcion", "La descripción no debe contener espacios al inicio o al final");
                    return View(detalle);
                }

                _DetallesBL.Guardardetalle(detalle);

                return RedirectToAction("Index");
            }

            return View(detalle);
        }

        public ActionResult Editar(int id)
        {
            var producto = _DetallesBL.Obtenerdetalle(id);

            return View(producto);
        }

        [HttpPost]
        public ActionResult Editar(detalle producto)
        {
            _DetallesBL.Guardardetalle(producto);

            return RedirectToAction("Index");
        }

        public ActionResult Detalle(int id)
        {
            var producto = _DetallesBL.Obtenerdetalle(id);

            return View(producto);
        }

        public ActionResult Eliminar(int id)
        {
            var producto = _DetallesBL.Obtenerdetalle(id);

            return View(producto);
        }

        [HttpPost]
        public ActionResult Eliminar(detalle producto)
        {
            _DetallesBL.Eliminardetalle(producto.Id);

            return RedirectToAction("Index");
        }
    }
}

EstadodeCuenta/EstadodeCuenta.WebAdmin/Controllers/TiposController.cs
using EstadodeCuenta.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstadodeCuenta.WebAdmin.Controllers
{
    public class TiposController : Controller
    {
        TiposBL _TiposBL;

        public TiposController()
        {
            _TiposBL = new TiposBL();
        }

        // GET: Tipos
        public ActionResult Index()
        {
            var listadeTipos = _TiposBL.ObtenerTipos();

            return View(listadeTipos);
        }

        public ActionResult Crear()
        {
            var nuevaTipo = new Tipo();

            return View(nuevaTipo);
        }

        [HttpPost]
        public ActionResult Crear(Tipo Tipo)
        {
            if (ModelState.IsValid)
            {
                if (Tipo.Descripcion != Tipo.Descripcion.Trim())
                {
                    ModelState.AddModelError("Descripcion", "La descripción no debe contener espacios al inicio o al final");
                    return View(Tipo);
                }

                _TiposBL.GuardarTipo(Tipo);

                return RedirectToAction("Index");
            }

            return View(Tipo);
        }

        public ActionResult Editar(int id)
        {
            var producto = _TiposBL.ObtenerTipo(id);

            return View(producto);
        }

        [HttpPost]
        public ActionResult Editar(Tipo producto)
        {
            _TiposBL.GuardarTipo(producto);

            return RedirectToAction("Index");
        }

        public ActionResult Detalle(int id)
        {
            var producto = _TiposBL.ObtenerTipo(id);

            return View(producto);
        }

        public ActionResult Eliminar(int id)
        {
            var producto = _TiposBL.ObtenerTipo(id);

            return View(producto);
        }

        [HttpPost]
        public ActionResult Eliminar(Tipo producto)
        {
            _TiposBL.EliminarTipo(producto.Id);

            return RedirectToAction("Index");
        }
    }
}

EstadodeCuenta/EstadodeCuenta.WebAdmin/Views/Tipos/Crear.cshtml
@model EstadodeCuenta.BL.Tipo

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EstadodeCuenta/EstadodeCuenta.WebAdmin/Views/Tipos/Detalle.cshtml
@model EstadodeCuenta.BL.Tipo

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Tipo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EstadodeCuenta/EstadodeCuenta.WebAdmin/Views/Tipos/Editar.cshtml
@model EstadodeCuenta.BL.Tipo

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EstadodeCuenta/EstadodeCuenta.WebAdmin/Views/Tipos/Eliminar.cshtml
@model EstadodeCuenta.BL.Tipo

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tipo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EstadodeCuenta/EstadodeCuenta.WebAdmin/Views/Tipos/Index.cshtml
@model IEnumerable<EstadodeCuenta.BL.Tipo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nuevo Tipo", "Crear", "Tipos", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Detalles", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>